### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by rtcmay** [gpambrozio/BambuAppDaemon#1]
not working i show you the log:

2024-08-20 05:05:10.089162 WARNING bambu: ------------------------------------------------------------
2024-08-20 05:06:25.278800 INFO AppDaemon: Terminating bambu
2024-08-20 05:06:25.285459 INFO AppDaemon: Reloading Module: /config/apps/bambu.py
2024-08-20 05:06:25.301960 INFO AppDaemon: Loading app bambu using class BambuImage from module bambu
2024-08-20 05:06:25.311360 INFO AppDaemon: Calling initialize() for bambu
2024-08-20 05:06:25.323821 WARNING bambu: ------------------------------------------------------------
2024-08-20 05:06:25.324826 WARNING bambu: Unexpected error running initialize() for bambu
2024-08-20 05:06:25.325951 WARNING bambu: ------------------------------------------------------------
2024-08-20 05:06:25.330227 WARNING bambu: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/bambu.py", line 21, in initialize
    self.listen_state(self.image_changed, self.image_entity)
                                          ^^^^^^^^^^^^^^^^^
AttributeError: 'BambuImage' object has no attribute 'image_entity'

2024-08-20 05:06:25.331305 WARNING bambu: ------------------------------------------------------------
2024-08-20 05:06:26.340519 WARNING bambu: ------------------------------------------------------------
2024-08-20 05:06:26.342261 WARNING bambu: Unexpected error in worker for App bambu:
2024-08-20 05:06:26.343528 WARNING bambu: Worker Ags: {'id': 'b4217f7866fe40cabed8da311bebcde8', 'name': 'bambu', 'objectid': 'f1e191d57c534962af78dc90970d5c74', 'type': 'scheduler', 'function': <bound method BambuImage.image_update of <bambu.BambuImage object at 0x7fba5ad350>>, 'pin_app': True, 'pin_thread': 1, 'kwargs': {'__thread_id': 'thread-1'}}
2024-08-20 05:06:26.345288 WARNING bambu: ------------------------------------------------------------
2024-08-20 05:06:26.350232 WARNING bambu: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1022, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/apps/bambu.py", line 27, in image_update
    image_url = self.get_entity(self.image_entity).get_state(attribute="entity_picture")
                                ^^^^^^^^^^^^^^^^^
AttributeError: 'BambuImage' object has no attribute 'image_entity'

2024-08-20 05:06:26.353185 WARNING bambu: ------------------------------------------------------------

**Comment by gpambrozio** [comment]
Seems you might be missing part of the instructions. When you added the app to your `apps.yaml`, did you include all parameters? It should look something like this:

```yaml
bambu:
  module: bambu
  class: BambuImage
  image_entity: "image.bambu_p1s_cover_image"
  ha_url: "http://home.local:8123"
  panda_ip: "192.168.86.88"
```

**Comment by rtcmay** [comment]
yes include all parameters

**Comment by rtcmay** [comment]
now show this:


[14:02:57] INFO: Starting AppDaemon...
2024-08-20 14:03:14.276069 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2024-08-20 14:03:14.291547 INFO AppDaemon: Python version is 3.11.9
2024-08-20 14:03:14.293820 INFO AppDaemon: Configuration read from: /config/appdaemon.yaml
2024-08-20 14:03:14.295131 INFO AppDaemon: Added log: AppDaemon
2024-08-20 14:03:14.296469 INFO AppDaemon: Added log: Error
2024-08-20 14:03:14.297962 INFO AppDaemon: Added log: Access
2024-08-20 14:03:14.299268 INFO AppDaemon: Added log: Diag
2024-08-20 14:03:15.379091 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2024-08-20 14:03:16.253955 INFO HASS: HASS Plugin Initializing
2024-08-20 14:03:16.254539 WARNING HASS: ha_url not found in HASS configuration - module not initialized
2024-08-20 14:03:16.255442 INFO HASS: HASS Plugin initialization complete
2024-08-20 14:03:16.257415 INFO AppDaemon: Initializing HTTP
2024-08-20 14:03:16.258853 INFO AppDaemon: Using 'ws' for event stream
2024-08-20 14:03:16.276464 INFO AppDaemon: Starting API
2024-08-20 14:03:16.286017 INFO AppDaemon: Starting Admin Interface
2024-08-20 14:03:16.287453 INFO AppDaemon: Starting Dashboards
2024-08-20 14:03:16.341852 INFO HASS: Connected to Home Assistant 2023.10.5
2024-08-20 14:03:16.379575 INFO AppDaemon: App 'bambu' added
2024-08-20 14:03:16.384311 INFO AppDaemon: Found 1 active apps
2024-08-20 14:03:16.385383 INFO AppDaemon: Found 0 inactive apps
2024-08-20 14:03:16.386502 INFO AppDaemon: Found 0 global libraries
2024-08-20 14:03:16.387866 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2024-08-20 14:03:16.391508 INFO AppDaemon: Running on port 5050
2024-08-20 14:03:16.541505 INFO HASS: Evaluating startup conditions
2024-08-20 14:03:16.571140 INFO HASS: Startup condition met: hass state=RUNNING
2024-08-20 14:03:16.572264 INFO HASS: All startup conditions met
2024-08-20 14:03:16.700698 INFO AppDaemon: Got initial state from namespace default
2024-08-20 14:03:18.412489 INFO AppDaemon: Scheduler running in realtime
2024-08-20 14:03:18.430811 INFO AppDaemon: Adding /config/apps to module import path
2024-08-20 14:03:18.435215 INFO AppDaemon: Loading App Module: /config/apps/bambu.py
2024-08-20 14:03:18.590879 WARNING Error: ------------------------------------------------------------
2024-08-20 14:03:18.591981 WARNING Error: Unexpected error loading module: /config/apps/bambu.py:
2024-08-20 14:03:18.593116 WARNING Error: ------------------------------------------------------------
2024-08-20 14:03:18.993437 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 1000, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 783, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/apps/bambu.py", line 6, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

2024-08-20 14:03:18.995264 WARNING Error: ------------------------------------------------------------
2024-08-20 14:03:18.998046 WARNING AppDaemon: Removing associated apps:
2024-08-20 14:03:19.000250 WARNING AppDaemon: bambu
2024-08-20 14:03:19.002125 INFO AppDaemon: App initialization complete

**Comment by kurim** [comment]
from the other thread: https://github.com/bigtreetech/PandaTouch/issues/108

> You'll need to add **Pillow** to **python_packages** section of the add on configuration. Make sure to also update app the parameters on the start of the file with the right image id and urls for your home assistant server and panda touch.

**Comment by gpambrozio** [comment]
I need to add this to the instructions:
* On Home assistant, go to Settings
* Open Add-Ons
* Click on AppDaemon
* Open the Configuration tab
* In "Python Packages", type "Pillow" (no quotes) and click enter.
* Click on the "Save" button.
* When asked, restart AppDaemon.

Please let me know if it works and I'll add to the instructions.

**Comment by kurim** [comment]
If it looks like this:
![image](https://github.com/user-attachments/assets/e01f5dfd-fe5f-44d5-ae16-a7af1cd53b36)

It "should" work, right?

**Comment by gpambrozio** [comment]
Mine has callbacks as 1 and state is Idle. I can't see your parameters.

![CleanShot 2024-08-20 at 09 21 07](https://github.com/user-attachments/assets/9d71e2ef-34d9-4e36-b530-5cdbe98adbbb)

**Comment by kurim** [comment]
it looks like this:
```yaml
{
    "module": "bambu",
    "class": "BambuImage",
    "image_entity": "image.p1s_01p00a361800220_titelbild",
    "ha_url": "http://homeassistant.local:8123",
    "panda_ip": "192.168.178.130"
}
```

**Comment by gpambrozio** [comment]
Can you post the AppDaemon logs please? Also, your "image_entity" looks a bit off. I believe it needs to end in "_cover_image"

**Comment by kurim** [comment]
image_entity is fine, it caused by the translation from ha-bambu
![image](https://github.com/user-attachments/assets/9113b226-cb95-4672-967c-2d3f98658e4d)

if this may a problem i can rename it

```log
[21:38:16] INFO: Starting AppDaemon...
2024-08-20 21:38:23.236434 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2024-08-20 21:38:23.237638 INFO AppDaemon: Python version is 3.11.9
2024-08-20 21:38:23.238314 INFO AppDaemon: Configuration read from: /config/appdaemon.yaml
2024-08-20 21:38:23.239698 INFO AppDaemon: Added log: AppDaemon
2024-08-20 21:38:23.240391 INFO AppDaemon: Added log: Error
2024-08-20 21:38:23.241840 INFO AppDaemon: Added log: Access
2024-08-20 21:38:23.243073 INFO AppDaemon: Added log: Diag
2024-08-20 21:38:23.645857 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2024-08-20 21:38:24.028330 INFO HASS: HASS Plugin Initializing
2024-08-20 21:38:24.028896 WARNING HASS: ha_url not found in HASS configuration - module not initialized
2024-08-20 21:38:24.029423 INFO HASS: HASS Plugin initialization complete
2024-08-20 21:38:24.030499 INFO AppDaemon: Initializing HTTP
2024-08-20 21:38:24.032062 INFO AppDaemon: Using 'ws' for event stream
2024-08-20 21:38:24.045127 INFO AppDaemon: Starting API
2024-08-20 21:38:24.051954 INFO AppDaemon: Starting Admin Interface
2024-08-20 21:38:24.053188 INFO AppDaemon: Starting Dashboards
2024-08-20 21:38:24.105481 INFO HASS: Connected to Home Assistant 2024.8.2
2024-08-20 21:38:24.149732 INFO AppDaemon: App 'bambu' added
2024-08-20 21:38:24.156301 INFO AppDaemon: Found 1 active apps
2024-08-20 21:38:24.156927 INFO AppDaemon: Found 0 inactive apps
2024-08-20 21:38:24.157393 INFO AppDaemon: Found 0 global libraries
2024-08-20 21:38:24.163500 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2024-08-20 21:38:24.166756 INFO AppDaemon: Running on port 5050
2024-08-20 21:38:24.247482 INFO HASS: Evaluating startup conditions
2024-08-20 21:38:24.264507 INFO HASS: Startup condition met: hass state=RUNNING
2024-08-20 21:38:24.265286 INFO HASS: All startup conditions met
2024-08-20 21:38:24.356434 INFO AppDaemon: Got initial state from namespace default
```

after change the name of the entity the log shows this:

```log
2024-08-20 21:41:52.528804 INFO AppDaemon: Reading config
2024-08-20 21:41:52.543940 INFO AppDaemon: /config/apps/apps.yaml added or modified
2024-08-20 21:41:52.545220 INFO AppDaemon: App 'bambu' changed
2024-08-20 21:41:52.550171 INFO AppDaemon: Found 1 active apps
2024-08-20 21:41:52.550534 INFO AppDaemon: Found 0 inactive apps
2024-08-20 21:41:52.551133 INFO AppDaemon: Found 0 global libraries
2024-08-20 21:41:52.555178 INFO AppDaemon: Terminating bambu
2024-08-20 21:41:52.556672 INFO AppDaemon: Loading app bambu using class BambuImage from module bambu
2024-08-20 21:41:52.557060 WARNING AppDaemon: Unable to find module module bambu - 'bambu' is not loaded
2024-08-20 21:41:52.558003 WARNING AppDaemon: Unable to find module bambu - initialize() skipped
2024-08-20 21:41:53.562785 INFO AppDaemon: Reading confi
```

**Comment by gpambrozio** [comment]
Weird, looks like hacs didn't download the app to the right place. In your `appdaemon.yaml`, do you have a custom `app_dir` configuration?

Also, do you have a `bambu` folder in your AppDaemon `apps` folder?

**Comment by kurim** [comment]
I can find the bambu.py here:
/homeassistant/appdaemon/apps/BambuAppDaemon/bambu.py

but it was not... here:
![image](https://github.com/user-attachments/assets/bb4b6f79-a17c-4c3a-8e70-5a20df920646)


after adding it there it works.

Could it cause by the reason that i have install first BambuAppDaemon and then AppDaemon addon?

Maybe i missed something in my Appdaemon config to add those path as search path (never used before)?

**Comment by gpambrozio** [comment]
Can you try changing your config to this:
```
{
    "module": "BambuAppDaemon",
    "class": "BambuImage",
    "image_entity": "image.p1s_01p00a361800220_titelbild",
    "ha_url": "http://homeassistant.local:8123",
    "panda_ip": "192.168.178.130"
}
```

**Comment by kurim** [comment]
has no effect.

```
2024-08-20 22:38:09.665533 INFO AppDaemon: Loading app bambu using class BambuImage from module BambuAppDaemon
2024-08-20 22:38:09.671703 WARNING AppDaemon: Unable to find module module BambuAppDaemon - 'bambu' is not loaded
2024-08-20 22:38:09.674256 WARNING AppDaemon: Unable to find module bambu - initialize() skipped
```

Setup:
Core 2024.8.2
Supervisor 2024.08.0
Operating System 13.0
Frontend 20240809.0

AppDaemon as Addon
Install BambuAppDaemon through HACS (like many other things)

**Comment by gpambrozio** [comment]
I just published release 0.1.2 that tries to fix this. Can you uninstall the current release and install the new one? Keep config as you have it now (with module as `BambuAppDaemon`) and post the logs if it doesn't work.

Thanks for trying it out.

**Comment by rtcmay** [comment]
finally.....working thanks bro.....

**Comment by gpambrozio** [comment]
Glad we got it working, thanks for helping me debug it.

**Comment by gpambrozio** [comment]
@kurim did you also get it working?

**Comment by kurim** [comment]
I have removed it and reinstall it.

Result:
![image](https://github.com/user-attachments/assets/27cf120a-1d45-417c-bff9-e8aaebfdd2da)


It will be stored here:
![image](https://github.com/user-attachments/assets/df40159e-b597-424a-bbf0-6bb3755d5bf2)

But the apps.yaml from the addon is here:

![image](https://github.com/user-attachments/assets/80f8f746-3dd6-424f-86c6-9fbc02719229)

It seems AppDaemon does not look for the py in the stored directory, did I miss something here?

Maybe this: https://github.com/hassio-addons/addon-appdaemon/pull/285

**Comment by gpambrozio** [comment]
I think you have an unusual configuration on your AppDaemon. I have it too and that's why I can't use the hacs install. Maybe use the manual installation instructions and try it out.

**Comment by kurim** [comment]
I just install it through the addons:
Home Assistant Community Add-on: AppDaemon
![image](https://github.com/user-attachments/assets/b2396ecf-0810-4a09-b319-11ed994cfc2f)

So I think this should be the correct way in HA OS to install it.

But since the config of the addon was moved away from normal config dir it resoults in the problem.

i have added: `app_dir: /homeassistant/appdaemon/apps/` to appdeamon.yaml to get it work

**Comment by phil-the-dev** [comment]
Just adding my experience here, as a bit of HS novice but technically inclined, I had these issues too. I had to add `app_dir` to the `appdaemon` group to get it to start actually calling the app.
